import 'package:flutter_test/flutter_test.dart';
import 'package:balloon_crumbs/domain/altitude.dart';
import 'package:balloon_crumbs/domain/imported_route.dart';

void main() {
  test('route JSON round-trip preserves geometry and metadata', () {
    final route = ImportedRoute(
      id: 'route-1',
      name: 'Saturday loop',
      description: 'Dry run',
      importedAt: DateTime.utc(2026, 7, 16, 9),
      sourceFileName: 'loop.gpx',
      purpose: ImportedRoutePurpose.balloonForecast,
      paths: [
        RoutePath(
          kind: RoutePathKind.track,
          name: 'Track one',
          points: [
            GeoPoint(
              latitude: 53.1,
              longitude: -1.4,
              elevationMeters: 210,
              altitudeSource: AltitudeSource.gnss,
              altitudeDatum: AltitudeDatum.wgs84Geoid,
              altitudeAccuracyMeters: 4.5,
              recordedAt: DateTime.utc(2026, 7, 16, 9, 1),
            ),
            const GeoPoint(latitude: 53.2, longitude: -1.5),
          ],
        ),
      ],
      waypoints: const [
        RouteWaypoint(
          point: GeoPoint(latitude: 53.3, longitude: -1.6),
          name: 'Fuel',
          description: 'Petrol station',
          symbol: 'Fuel',
        ),
      ],
      maneuvers: const [
        RouteManeuver(
          position: GeoPoint(latitude: 53.2, longitude: -1.5),
          type: 'roundabout',
          modifier: 'right',
          name: 'High Street',
          ref: 'A1',
          exitNumber: 3,
          drivingSide: 'left',
          bearingBeforeDegrees: 91,
          bearingAfterDegrees: 182,
          lanes: [
            RouteLane(indications: ['left'], valid: false),
            RouteLane(indications: ['straight', 'right'], valid: true),
          ],
        ),
      ],
      plannedDuration: const Duration(minutes: 42),
    );

    final restored = ImportedRoute.fromJsonString(route.toJsonString());

    expect(restored.id, 'route-1');
    expect(restored.name, 'Saturday loop');
    expect(restored.pathPointCount, 2);
    expect(restored.paths.single.kind, RoutePathKind.track);
    expect(restored.purpose, ImportedRoutePurpose.balloonForecast);
    expect(restored.paths.single.points.first.elevationMeters, 210);
    expect(
      restored.paths.single.points.first.altitudeSource,
      AltitudeSource.gnss,
    );
    expect(
      restored.paths.single.points.first.altitudeDatum,
      AltitudeDatum.wgs84Geoid,
    );
    expect(restored.paths.single.points.first.altitudeAccuracyMeters, 4.5);
    expect(restored.waypoints.single.name, 'Fuel');
    expect(restored.maneuvers.single.type, 'roundabout');
    expect(restored.maneuvers.single.modifier, 'right');
    expect(restored.maneuvers.single.name, 'High Street');
    expect(restored.maneuvers.single.exitNumber, 3);
    expect(restored.maneuvers.single.drivingSide, 'left');
    expect(restored.maneuvers.single.bearingBeforeDegrees, 91);
    expect(restored.maneuvers.single.bearingAfterDegrees, 182);
    expect(restored.maneuvers.single.lanes, hasLength(2));
    expect(restored.maneuvers.single.lanes.last.valid, isTrue);
    expect(restored.plannedDuration, const Duration(minutes: 42));
  });

  test('a route saved before bearings existed still loads', () {
    final restored = ImportedRoute.fromJson({
      'schemaVersion': 1,
      'id': 'legacy',
      'name': 'Legacy route',
      'importedAt': '2026-07-01T00:00:00.000Z',
      'sourceFileName': 'legacy.gpx',
      'paths': [
        {
          'kind': 'track',
          'points': [
            {'latitude': 53.1, 'longitude': -1.4},
            {'latitude': 53.2, 'longitude': -1.5},
          ],
        },
      ],
      'waypoints': const [],
      'maneuvers': [
        {
          'latitude': 53.2,
          'longitude': -1.5,
          'type': 'roundabout',
          'modifier': 'slight left',
          'exitNumber': 2,
        },
      ],
    });

    expect(restored.maneuvers.single.bearingBeforeDegrees, isNull);
    expect(restored.maneuvers.single.bearingAfterDegrees, isNull);
    expect(restored.maneuvers.single.exitNumber, 2);
    expect(
      restored.paths.single.points.first.altitudeSource,
      AltitudeSource.unknown,
    );
    expect(
      restored.paths.single.points.first.altitudeDatum,
      AltitudeDatum.unknown,
    );
    expect(restored.purpose, ImportedRoutePurpose.unspecified);
  });

  test('migrates the planned duration from a build 60 destination route', () {
    final restored = ImportedRoute.fromJson({
      'schemaVersion': 1,
      'id': 'legacy-destination',
      'name': 'To Chippenham',
      'description':
          'Road route generated by Balloon Crumbs. 17.3 mi, 1 hr 12 min. Twisty.',
      'importedAt': '2026-08-15T00:00:00.000Z',
      'sourceFileName': 'balloon-crumbs-destination-old.gpx',
      'paths': [
        {
          'kind': 'track',
          'points': [
            {'latitude': 51.4, 'longitude': -2.5},
            {'latitude': 51.5, 'longitude': -2.4},
          ],
        },
      ],
      'waypoints': const [],
    });

    expect(restored.plannedDuration, const Duration(hours: 1, minutes: 12));
  });
}
