import 'dart:convert';

import 'package:flutter/services.dart';
import 'package:uuid/uuid.dart';

import '../domain/geo_point.dart';
// Routes carry their own GeoPoint, which has a timestamp on it. The flight uses
// the plain domain one, so the route's is hidden rather than prefixed here.
import '../domain/imported_route.dart' hide GeoPoint;
import 'gpx_parser.dart';

/// One moment of the balloon's flight: where it was, how high, and when.
class BalloonFlightSample {
  const BalloonFlightSample({
    required this.position,
    required this.heightMetres,
    required this.elapsed,
  });

  final GeoPoint position;

  /// Height above the launch field, which is what a pilot flies and what the
  /// chase crew is told over the radio. Not an altitude above sea level.
  final double heightMetres;

  final Duration elapsed;
}

/// A wind layer, as measured rather than as imagined.
class BalloonWindLayer {
  const BalloonWindLayer({
    required this.heightMetres,
    required this.fromDegrees,
    required this.speedKmh,
  });

  final double heightMetres;

  /// The direction the wind comes *from*, the convention every forecast and
  /// every pilot uses. Drift is the reciprocal, and confusing the two is how a
  /// chase ends up on the wrong side of a city.
  final double fromDegrees;

  final double speedKmh;

  double get towardDegrees => (fromDegrees + 180) % 360;
}

/// The bundled Bristol Fiesta flight.
///
/// Generated by `tools/simulation/bristol_fiesta_flight.py` from the winds
/// measured over Ashton Court for the dawn mass ascent of Saturday 8 August
/// 2026. Bundled rather than computed at runtime, and bundled rather than
/// fetched, because the simulator exists to rehearse a rural retrieve with no
/// signal — a demo that needs the network to start could not be run at the
/// place it is meant to describe.
class BalloonFlight {
  const BalloonFlight({
    required this.name,
    required this.launch,
    required this.samples,
    required this.windLayers,
    required this.source,
  });

  final String name;
  final GeoPoint launch;
  final List<BalloonFlightSample> samples;
  final List<BalloonWindLayer> windLayers;

  /// Provenance, carried so a surface can say where the numbers came from.
  final String source;

  GeoPoint get landing => samples.last.position;
  Duration get duration => samples.last.elapsed;
  double get peakHeightMetres => samples
      .map((sample) => sample.heightMetres)
      .reduce((a, b) => a > b ? a : b);

  List<GeoPoint> get track =>
      List.unmodifiable(samples.map((sample) => sample.position));
}

class BundledFiestaFlightLoader {
  const BundledFiestaFlightLoader();

  static const flightAsset = 'assets/simulation/fiesta_balloon_flight.json';
  static const chaseRouteAsset = 'assets/simulation/fiesta_chase_route.gpx';

  /// The road route the chase crew drives, Ashton Court to the landing field.
  ///
  /// A separate asset from the flight on purpose. The crew cannot follow the air
  /// track - it crosses the Ashton Court estate, the A370, farmland and a
  /// railway - so the route they navigate is 13.4 km of road against 8.9 km of
  /// drift. Loading one and pretending it serves both is what the old demo did.
  Future<ImportedRoute> loadChaseRoute() async {
    final data = await rootBundle.load(chaseRouteAsset);
    return const GpxParser().parse(
      data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes),
      routeId: const Uuid().v4(),
      sourceFileName: 'fiesta_chase_route.gpx',
      importedAt: DateTime.now(),
    );
  }

  Future<BalloonFlight> load() async {
    final decoded = jsonDecode(await rootBundle.loadString(flightAsset));
    if (decoded is! Map) {
      throw const FormatException(
        'The bundled Fiesta flight is not an object.',
      );
    }
    final samples = decoded['samples'];
    if (samples is! List || samples.length < 2) {
      throw const FormatException(
        'The bundled Fiesta flight needs at least two samples.',
      );
    }
    final launch = decoded['launch'];
    if (launch is! Map) {
      throw const FormatException('The bundled Fiesta flight has no launch.');
    }
    return BalloonFlight(
      name: decoded['name'] as String? ?? 'Balloon flight',
      launch: GeoPoint(
        latitude: (launch['latitude'] as num).toDouble(),
        longitude: (launch['longitude'] as num).toDouble(),
      ),
      source: decoded['source'] as String? ?? '',
      windLayers: [
        for (final layer
            in (decoded['windLayers'] as List? ?? []).whereType<Map>())
          BalloonWindLayer(
            heightMetres: (layer['heightMetres'] as num).toDouble(),
            fromDegrees: (layer['fromDegrees'] as num).toDouble(),
            speedKmh: (layer['speedKmh'] as num).toDouble(),
          ),
      ],
      samples: [
        for (final sample in samples.whereType<Map>())
          BalloonFlightSample(
            position: GeoPoint(
              latitude: (sample['latitude'] as num).toDouble(),
              longitude: (sample['longitude'] as num).toDouble(),
            ),
            heightMetres: (sample['heightMetres'] as num).toDouble(),
            elapsed: Duration(seconds: (sample['seconds'] as num).round()),
          ),
      ],
    );
  }
}
